/*
    SCRIPT QUE CREA LAS TABLAS EN LAS CUALES SE HARÁ EL ALMACENAMIENTO DE LOS DATOS
    EJECUTAR DE PRIMERO
*/    
    DROP TABLE PEDIDOS;
    DROP TABLE DESCANSOS;
    DROP SEQUENCE pedidos_id;

    /*TABLA QUE CONTIENE LOS DATOS DE LOS PEDIDOS
    EL NUMERO DEL PEDIDO, FECHA DE RECEPCION, TIEMPO ESTIMADO DE ENTREGA,
    ESTADO DEL PEDIDO Y FECHA DE ENTREGA*/
    CREATE TABLE PEDIDOS 
        (NUM_PED NUMBER(9) PRIMARY KEY,
         RECIBIDO DATE,
         TIEMPO_EST NUMBER (3),
         ESTATUS NUMBER(1),
         ENTREGADO DATE --ESTE VALOR POR DEFECTO ESTARÁ EN NULL, POSTERIORMENTE SE ACTUALIZARÁ
        );
    
        
     /*TABLA QUE MUESTRA EL ESTADO DE LOS DESCANSOS DEL TRABAJADOR
     LOS MISMOS INFLUYEN EN EL CÁLCULO DEL TIEMPO */
     CREATE TABLE DESCANSOS
        (DESCRIPCION VARCHAR(30),
         FECHA_INIC DATE,
         FECHA_FINAL DATE
        );
        
     /*CREACION DE SECUENCIA PARA LA TABLA PEDIDOS*/
     CREATE SEQUENCE pedidos_id
        START WITH 1000 INCREMENT BY 1
        MAXVALUE 10000000;