
--SCRIPT EN DONDE SE REALIZA LA EJECUCION DEL PROGRAMA CREADO
BEGIN
    CALCULO_PEDIDOS.UPD_FECHA;
END;

SELECT NUM_PED,TO_CHAR(RECIBIDO, 'DD-MM-YYYY HH24:MI:SS') RECEPCION, ESTATUS,
        TO_CHAR(ENTREGADO, 'DD-MM-YYYY HH24:MI:SS') ENTREGA
FROM PEDIDOS;