SELECT COLUMN_NAME NOMBRE_COLUMNA, DATA_TYPE "TIPO DE DATO", DATA_LENGTH "LONGITUD",
       GLOBAL_STATS "STATUS" ,NULLABLE "NULL A/NA"
FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME = '&NOMBRE' AND OWNER = 'HR';

