/*BLOQUE EJ2*/
DECLARE VARIABLE_2 VARCHAR2(100):='';

BEGIN 

    DECLARE VARIABLE_1 VARCHAR2(100):=''; 

    BEGIN 

        VARIABLE_1 := 'HOLA MUNDO'; 
        VARIABLE_2 := 'HOLA MUNDO'; 

    END; 

    DBMS_OUTPUT.PUT_LINE(VARIABLE_2);

END;